name: sdm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=openblas
  - bottleneck=1.3.5=py38h67323c0_0
  - brotli=1.0.9=hb1e8313_2
  - brotli-python=1.0.9=py38h4cd09af_9
  - ca-certificates=2023.08.22=hecd8cb5_0
  - certifi=2023.7.22=py38hecd8cb5_0
  - charset-normalizer=3.3.0=pyhd8ed1ab_0
  - contourpy=1.0.5=py38haf03e11_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=py38hecd8cb5_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=hd8bbffd_0
  - giflib=5.2.1=h6c40b1e_3
  - idna=3.4=pyhd8ed1ab_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - jdcal=1.4.1=pyhd3eb1b0_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h6c40b1e_1
  - kiwisolver=1.4.4=py38hcec6c5f_0
  - kneed=0.8.5=pyhd8ed1ab_0
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libblas=3.9.0=19_osx64_openblas
  - libcblas=3.9.0=19_osx64_openblas
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.17=hb664fd8_1
  - libffi=3.4.4=hecd8cb5_0
  - libgfortran=5.0.0=13_2_0_h97931a8_1
  - libgfortran5=13.2.0=h2873a65_1
  - liblapack=3.9.0=19_osx64_openblas
  - libopenblas=0.3.24=openmp_h48a4ad5_0
  - libpng=1.6.39=h6c40b1e_0
  - libtiff=4.5.1=hcec6c5f_0
  - libwebp=1.3.2=hf6ce154_0
  - libwebp-base=1.3.2=h6c40b1e_0
  - llvm-openmp=17.0.2=hff08bdf_0
  - lz4-c=1.9.4=hcec6c5f_0
  - matplotlib=3.7.2=py38hecd8cb5_0
  - matplotlib-base=3.7.2=py38hee32256_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=hcec6c5f_0
  - numexpr=2.8.4=py38h57a7bef_1
  - numpy=1.24.3=py38h57a7bef_0
  - numpy-base=1.24.3=py38hc93c6d9_0
  - openjpeg=2.4.0=h66ea3da_0
  - openpyxl=3.0.7=pyhd3eb1b0_0
  - openssl=3.0.11=hca72f7f_2
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=1.4.4=py38he9d5cce_0
  - pillow=10.0.1=py38h7d39338_0
  - pip=23.3=py38hecd8cb5_0
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyhd8ed1ab_4
  - pyparsing=3.0.9=py38hecd8cb5_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.18=h5ee71fb_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2023.3.post1=py38hecd8cb5_0
  - readline=8.2=hca72f7f_0
  - requests=2.31.0=pyhd8ed1ab_0
  - scikit-learn=1.2.2=py38h1081964_1
  - scipy=1.10.1=py38h9034365_1
  - setuptools=68.0.0=py38hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h6c40b1e_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.12=h5d9f67b_0
  - tornado=6.3.3=py38h6c40b1e_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - urllib3=2.0.6=pyhd8ed1ab_0
  - wheel=0.41.2=py38hecd8cb5_0
  - xlsxwriter=1.3.7=pyhd3eb1b0_0
  - xz=5.4.2=h6c40b1e_0
  - zipp=3.11.0=py38hecd8cb5_0
  - zlib=1.2.13=h4dc903c_0
  - zstd=1.5.5=hc035e20_0
prefix: /Users/nathandidier/opt/anaconda3/envs/sdm_env
